site_name: Village Folk
# theme_dir: alabaster
theme: readthedocs
extra_css: [extra.css]

site_description: An OSR rulebook.
site_author: Michael Bacon
include_sidebar: true

markdown_extensions:
    - smarty
    - toc:
        permalink: True
        anchorlink: True

pages:
      - Introduction: index.md
      - Adventuring: Adventuring.md
      - Checks: Checks.md
      - Classes, Caster: ClassesCasters.md
      - Classes, Exorcist: ClassesExorcists.md
      - Classes, Expert: ClassesExpert.md
      - Classes, Martial: ClassesMartial.md
      - Classes, Racial: ClassesRacial.md
      - Classes, Weird: ClassesWeird.md
      - Combat: Combat.md
      - Conversation: Conversation.md
      - Curses: Curses.md
      - Death and Dismemberment: Death_Dismemberment.md
      - Exploding Damage: Exploding_Damage.md
      - Extras: Extras.md
      - GM Advice: GM_advice.md
      - Light Source, Checks: Light_Source_Checks.md
      - Light Source, Traditional: Light_Source_Traditional.md
      - Magic: Magic.md
      - Market: Market.md
      - Movement: Movement.md
      - Player Advice: PlayerAdvice.md
      - Play Procedure: Play_Procedure.md
      - Player Rules/Character Generation: PlayerRules.md
      - Professions: Professions.md
#     - Random Starting Items: Starting items.md
      - Skills: Skills.md
      - Saving Throw, Charisma + Level: Saving_Throw_Charisma+Level.md
      - Saving Throw, Half Stat: Saving_Throw_Half_Stat
      - Saving Throw, Half Stat -- Complex: Saving_Throw_Half_Stat_Complex.md
      - Solo Player Character: SoloPC.md
      - License: zGame_License.md
