site_name: Modular GLOG
# theme_dir: alabaster
theme: readthedocs
extra_css: [extra.css]

site_description: A Modular OSR Rulebook. Take what you want.
site_author: Michael Bacon
include_sidebar: true

markdown_extensions:
    - smarty
    - toc:
        permalink: True
        anchorlink: True

pages:
      - Introduction: index.md
      - Adventuring: Adventuring.md
      - Checks: Checks.md
      - Classes, Caster: ClassesCasters.md
      - Classes, Exorcist: ClassesExorcists.md
      - Classes, Expert: ClassesExpert.md
      - Classes, Martial: ClassesMartial.md
      - Classes, Racial: ClassesRacial.md
      - Classes, Weird: ClassesWeird.md
      - Combat: Combat.md
      - Conversation: Conversation.md
      - Curses: Curses.md
      - Death and Dismemberment: Death_Dismemberment.md
      - Exploding Damage Die: Exploding_Damage_Die.md
      - Extras: Extras.md
      - GM Advice: GM_advice.md
      - Inventory Cards: Inventory_Cards.md
      - Light Source, Checks: Light_Source_Checks.md
      - Light Source, Traditional: Light_Source_Traditional.md
      - Magic: Magic.md
      - Market: Market.md
      - Movement: Movement.md
      - Mutation: Mutation.md
      - Overland Actions: Overland_Actions.md
      - Overland Basics: Overland_Basics.md
      - Overland Encounters, by Terrain: Overland_Encounters_by_Terrain.md
      - Overland Encounters, Simple: Overland_Encounters_Simple.md
      - Overland Travel: Overland_Travel.md
      - Overland Travel, Traditional: Overland_Travel_Traditional.md
      - Player Advice: Player_Advice.md
      - Player Rules/Character Generation: Player_Rules_Character_Generation.md
      - Play Procedure: Play_Procedure.md
      - Professions: Professions.md
      - Random Starting Items: Random_Starting_Items.md
      - Saving Throw, Charisma + Level: Saving_Throw_Charisma+Level.md
      - Saving Throw, Half Stat: Saving_Throw_Half_Stat.md
      - Saving Throw, Half Stat -- Improving: Saving_Throw_Half_Stat_Improving.md
      - Skills: Skills.md
      - Solo Player Character: SoloPC.md
      - License: zGame_License.md
