site_name: Modular GLOG
theme: readthedocs
extra_css: [extra.css]

site_description: A Modular OSR Rulebook. Take what you want.
site_author: Michael Bacon and Everyone Else
include_sidebar: true

markdown_extensions:
    - smarty
    - toc:
        permalink: True
        anchorlink: True

pages:
      - Introduction: index.md
      - Adventuring: Adventuring.md
      - Checks: Checks.md
      - Class Caster Blue: Class_Caster_Blue.md
      - Class Caster Bug Collector: Class_Caster_Bug_Collector.md
      - Class Caster Humble Art: Class_Caster_Humble_Art.md
      - Class Caster Summoner: Class_Caster_Summoner.md
      - Class Exorcist General: Class_Exorcist_General.md 
      - Class Exorcist Bell: Class_Exorcist_Bell.md 
      - Class Exorcist Book: Class_Exorcist_Book.md 
      - Class Exorcist Sword: Class_Exorcist_Sword.md
      - Class Expert Engineer: Class_Expert_Engineer.md
      - Class Expert Goliard: Class_Expert_Goliard.md
      - Class Expert Monk or Nun: Class_Expert_Monk_or_Nun.md
      - Class Expert Scoundrel: Class_Expert_Scoundrel.md 
      - Class Expert Thief: Class_Expert_Thief.md
      - Class Expert Professions: Class_Expert_Professions.md
      - Class Martial Barbarian: Class_Martial_Barbarian.md
      - Class Martial Fighter: Class_Martial_Fighter.md
      - Class Martial Paladin of the Word: Class_Martial_Paladin_of_the_Word.md
      - Class Racial Dwarf: Class_Racial_Dwarf.md
      - Class Weird Possessing Weapon: Class_Weird_Possessing_Weapon.md
      - Class Weird Really Good Dog: Class_Weird_Really_Good_Dog.md
      - Class Wizard General: Class_Wizard_General.md
      - Class Wizard Animist: Class_Wizard_Animist.md
      - Class Wizard Biomancer: Class_Wizard_Biomancer.md 
      - Class Wizard Door: Class_Wizard_Door.md
      - Class Wizard Drowned: Class_Wizard_Drowned.md
      - Class Wizard Elementalist: Class_Wizard_Elementalist.md 
      - Class Wizard Elf: Class_Wizard_Elf.md 
      - Class Wizard Garden: Class_Wizard_Garden.md 
      - Class Wizard Necromancer: Class_Wizard_Necromancer.md
      - Class Wizard Orthodox: Class_Wizard_Orthodox.md
      - Class Wizard Spider: Class_Wizard_Spider.md 
      - Class Wizard White Hand: Class_Wizard_White_Hand.md
      - Combat: Combat.md
      - Conversation: Conversation.md
      - Curses: Curses.md
      - Death and Dismemberment: Death_Dismemberment.md
      - Exploding Damage Die: Exploding_Damage_Die.md
      - GM Advice: GM_advice.md
      - Inventory Cards: Inventory_Cards.md
      - Light Source, Checks: Light_Source_Checks.md
      - Light Source, Traditional: Light_Source_Traditional.md
      - Magic: Magic.md
      - Market: Market.md
      - Movement: Movement.md
      - Mutation: Mutation.md
      - Overland Actions: Overland_Actions.md
      - Overland Basics: Overland_Basics.md
      - Overland Encounters, by Terrain: Overland_Encounters_by_Terrain.md
      - Overland Encounters, Simple: Overland_Encounters_Simple.md
      - Overland Travel: Overland_Travel.md
      - Overland Travel, Traditional: Overland_Travel_Traditional.md
      - Player Advice: Player_Advice.md
      - Player Rules/Character Generation: Player_Rules_Character_Generation.md
      - Play Procedure: Play_Procedure.md
      - Professions: Professions.md
      - Random Starting Items: Random_Starting_Items.md
      - Saving Throw, Charisma + Level: Saving_Throw_Charisma+Level.md
      - Saving Throw, Half Stat: Saving_Throw_Half_Stat.md
      - Saving Throw, Half Stat -- Improving: Saving_Throw_Half_Stat_Improving.md
      - Skills: Skills.md
      - Solo Player Character: SoloPC.md
      - License: zGame_License.md
