site_name: Modular OSR Library
theme: readthedocs
extra_css: [extra.css]

site_description: Modular OSR Library. Take what you want.
site_author: Michael Bacon and Everyone Else
include_sidebar: true

markdown_extensions:
    - smarty
    - toc:
        permalink: True
        anchorlink: True

pages:
      - Introduction: index.md
